# Generated by Django 5.1.5 on 2025-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
    ]
