# Generated by Django 5.1.5 on 2025-04-10 08:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='dateOfJoining',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
