# Generated by Django 5.1.5 on 2025-04-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactnumber', models.CharField(max_length=12)),
                ('dateOfAdmission', models.DateField()),
            ],
        ),
    ]
