# Generated by Django 5.1.5 on 2025-02-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
